### ISSUE TITLE
cannot be built

### ISSUE THREAD

**Issue by LIUQyou** [mmavrop/Cache-Fault-Tolerant-Gem5-Simulator#1]
Hi Mr.Mavropoulos,

I am interested in your project, and I am studying the cache policy as well. But I encounter a problem when I trying to build it from the source.

I used the instruction "python3 `which scons` build/X86/gem5.opt -j9". Then it will generate error. 

Could you give me some advice?

Thanks.

Liu

**Comment by mmavrop** [comment]
Hello Mr. Liu,

Thank you for your question.

Please downgrade the python version to 2.7. This project has been branched out from gem5 commit id "9d3b9e96c56386ee6539657c21cba95e118e576a" which is not compatible with python3.  

Inform me the results. 

Cheers, 
Michail M.

**Comment by LIUQyou** [comment]
Thanks!
It works. :D

**Comment by mmavrop** [comment]
Welcome!
Feel free to raise a new issue in case you face any trouble with this project.
